import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().port().default(3000),
  DB_HOST: Joi.string().default('localhost'),
  DB_PORT: Joi.number().default(5432),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_NAME: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_ACCESS_EXPIRATION: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRATION: Joi.string().default('7d'),
  CONFIRMATION_TOKEN_EXPIRATION_HOURS: Joi.number().default(1),
  PASSWORD_RESET_TOKEN_EXPIRATION_HOURS: Joi.number().default(1),
  APP_URL: Joi.string().uri().default('http://localhost:3000'),
  MAIL_HOST: Joi.string().default('mailpit'),
  MAIL_PORT: Joi.number().default(1025),
  MAIL_FROM: Joi.string().default('"StreamTube" <noreply@streamtube.com>'),
  SWAGGER_ENABLED: Joi.string().valid('true', 'false').default('false'),
  STORAGE_ENDPOINT: Joi.string().uri().default('http://minio:9000'),
  STORAGE_REGION: Joi.string().default('us-east-1'),
  STORAGE_ACCESS_KEY: Joi.string().required(),
  STORAGE_SECRET_KEY: Joi.string().required(),
  STORAGE_BUCKET: Joi.string().default('streamtube'),
  STORAGE_FORCE_PATH_STYLE: Joi.string().valid('true', 'false').default('true'),
  REDIS_HOST: Joi.string().default('redis'),
  REDIS_PORT: Joi.number().port().default(6379),
  VIDEO_QUEUE_ATTEMPTS: Joi.number().min(1).default(3),
  VIDEO_QUEUE_BACKOFF_MS: Joi.number().min(0).default(5000),
  VIDEO_QUEUE_LOCK_DURATION_MS: Joi.number().min(1000).default(600000),
  VIDEO_QUEUE_CONCURRENCY: Joi.number().min(1).default(1),
  VIDEO_MAX_SIZE_BYTES: Joi.number().min(1).default(10737418240),
  // S3 requires every part except the last to be at least 5MiB.
  VIDEO_UPLOAD_PART_SIZE_BYTES: Joi.number().min(5242880).default(67108864),
  VIDEO_UPLOAD_URL_TTL_SECONDS: Joi.number().min(60).default(3600),
  VIDEO_THUMBNAIL_POSITION_RATIO: Joi.number().min(0).max(1).default(0.1),
  VIDEO_THUMBNAIL_WIDTH: Joi.number().min(16).default(1280),
});
